version: '2'
services:
    monolit-app:
        image: monolit
        external_links:
            - monolit-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/monolit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    monolit-mysql:
        extends:
            file: mysql.yml
            service: monolit-mysql
